!=====================================================================
!=====================================================================
!
!			SUBROUTINE FORW
!
!> this subroutine traces ray for a single event to single station
!! thus it is called foreach station per event.
!!
!!  NOTE THIS IS ALSO THE SUBROUTINE THAT COMPUTES THE G_MATRIX KERNEL
!
! params sent:  velco, bazin, rayparam, ist, ieq
! 
! params returned:  tt_pred, slow (slowness array (not_used),traveltime_pred)
!
! Called by FRECHET
! Calls  RAYWEB (TTIME(VEL3(INTMAP)))
!        SIMPLEX (TTIME2(VEL3(INTMAP)),SORT(SWITCH),SWITCH)
!        TTMDER (GMATRIX,VEL3(INTMAP))
!
!=====================================================================
!=====================================================================
    !INCLUDE 'INTERF/MOD_rayweb.f'
    !INCLUDE 'INTERF/MOD_simplex.f'
    !INCLUDE 'INTERF/MOD_ttmder.f'
    
    SUBROUTINE FORW(velco,nr,nrp,bazin,rayparm,ieq,stc,ist,G,&
                    vxnodes,vynodes,vznodes,fstime)

      USE MOD_unit
      USE MOD_layer
      USE MOD_vdata
      USE MOD_size
      USE MOD_iloc

      USE MOD_rayweb
      USE MOD_simplex
      USE MOD_ttmder
      USE MOD_vel3

      IMPLICIT NONE
!=====================================================================
! Declaration of the in/out arguments of FORW
!=====================================================================
      integer,intent(in)                       :: nr
      integer,intent(out)                      :: nrp
      integer,DIMENSION(:),pointer             :: ieq,ist

      real(kind=8),intent(out)                 :: fstime
      real(kind=8),DIMENSION(:),intent(in)     :: velco
      real(kind=8),DIMENSION(:),intent(in)     :: vxnodes,vynodes,vznodes
      real(kind=8),DIMENSION(:),pointer        :: rayparm,bazin
      real(kind=8),DIMENSION(:,:),intent(inout):: G
      real(kind=8),DIMENSION(:,:),pointer      :: stc

!=====================================================================
! Declaration of the dummy arguments of FORW
!=====================================================================
      integer                   :: i

      real(kind=8)              :: xs,ys,zs,xe,ye,ze
      real(kind=8)              :: dummy,xhypo,yhypo
      real(kind=8)              :: path
      real(kind=8)              :: twopi
      real(kind=8),DIMENSION(:,:),ALLOCATABLE   :: rp
!=====================================================================
! Initialization of constant twopi and allocation of memory
!=====================================================================
      twopi = 8.d0 * datan(1.d0)
      ALLOCATE (rp(3,iarsize))
!=====================================================================
! Store station location in dummy array
!=====================================================================
      xs=stc(ist(nr),1)
      ys=stc(ist(nr),2)
      zs=stc(ist(nr),3)
        
      dummy = (zlayerdepth - zs)*dtan(dasin (vhalf*rayparm(nr)))
      
      yhypo = dummy * dcos(twopi/360.d0 * bazin(nr))
      xhypo = dummy * dsin(twopi/360.d0 * bazin(nr))
      xe = xhypo + xs
      ye = yhypo + ys
      ze = zlayerdepth
!=====================================================================
!  Determine the straight line travel-time now.
!=====================================================================
        
      CALL RAYWEB(xe,ye,ze,xs,ys,zs,fstime,rp,nrp,velco,nr)

!=====================================================================
! apply three dimensional raytracing if i3d=1
!=====================================================================
      if (i3d .eq. 1) then
         CALL SIMPLEX (nrp,fstime,rp,velco)
!           CALL TTIME3(nrp,rp,fstime,path,velco,vznodes)
      end if
!=====================================================================
! put the new raypath into raypath4gmt file
!=====================================================================
        
      do i=1,nrp
         write(raypath,'(3(f10.4,2x))') rp(1,i),rp(2,i),rp(3,i)
      end do

!=====================================================================
! save the travel time
!=====================================================================

      CALL TTMDER(G,nr,nrp,rp,velco,vxnodes,vynodes,vznodes)

      DEALLOCATE (rp)

    END SUBROUTINE FORW


!=====================================================================
!=====================================================================
!
!			SUBROUTINE TTIME3
!
! This routine calculates the travel time of the raypath
! generated by the simplex routine.  It differs from 
! subroutine ttime only in that it works with a raypath
! dimensioned pth(3) rather than pth(3*iarsize) as in ttime.
!
! Called by FORW
! Calls VEL3
!
!=====================================================================
!=====================================================================
    SUBROUTINE TTIME3(nrp,pth,tt,dpath,velco,vznodes)

      USE MOD_size
      USE MOD_iloc
      USE MOD_layer

      USE MOD_vel3

      IMPLICIT NONE

!=====================================================================
! Declaration of the in/out arguments of TTIME3
!=====================================================================
      integer,intent(in)                     :: nrp

      real(kind=8),intent(out)               :: tt,dpath
      real(kind=8),DIMENSION(:,:),intent(in) :: pth
      real(kind=8),DIMENSION(:),intent(in)   :: velco,vznodes
!=====================================================================
! Declaration of the dummy arguments of TTIME3
!=====================================================================
      integer                                :: i,i1,ip,jp,kp

      real(kind=8)                           :: dt,x,y,z,v,psep
      real(kind=8)                           :: dx2,dy2,dz2
      real(kind=8),DIMENSION(:),ALLOCATABLE  :: v1

!=====================================================================
! Initialization of some variables and Allocation of v1
!=====================================================================
      tt=0.0d0
      dt=0.0d0
      dpath=0.0d0

      ALLOCATE (v1(iarsize))
!=====================================================================
! Find velocities along the raypath.
!=====================================================================
      do i=1,nrp
         x=pth(1,i)
         y=pth(2,i)
         z=pth(3,i)
         CALL VEL3(x,y,z,v,velco,ip,jp,kp)
         v1(i)=v
      end do
!=====================================================================
! Calculate the travel time.
!=====================================================================
      do i=2,nrp
         i1=i-1
         if (pth(3,i) .le. (vznodes(nznode-1) - 1)) then
            dz2 = pth(3,i)-pth(3,i1)
            dx2 = pth(1,i)-pth(1,i1)
            dy2 = pth(2,i)-pth(2,i1)
            psep = dsqrt( dx2*dx2 + dy2*dy2 + dz2*dz2)
            if (v1(i).ne.0.d0 .and. v1(i1).ne.0.0d0 ) then
               dt = psep * ( 1.0d0/v1(i) + 1.0d0/v1(i1) )
            end if
            dpath = dpath + psep
            tt = tt+dt
         end if
      end do

      tt = 0.5d0 * tt
!=====================================================================
! Deallocation of the dummy array v1
!=====================================================================
      DEALLOCATE (v1)

    END SUBROUTINE TTIME3
